name: Daily API Report

on:
  schedule:
    # Ejecuta cada 3 horas 
    - cron: '0 22 * * *'
  
  # Permite ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send API Report
        run: |
          set -euo pipefail
          BASE_URL="${{ secrets.APP_URL }}"
          # Normalizar para evitar doble '/'
          BASE_URL="${BASE_URL%/}"
          URL="${BASE_URL}/trigger-report"
          
          echo "Checking health at: ${BASE_URL}/health"
          curl -sS -o /dev/null -w "Health HTTP Status: %{http_code}\n" "${BASE_URL}/health" || true
          
          echo "Triggering report at: $URL"
          
          # Enviar POST sin parámetros de fecha (el sistema usa la fecha actual)
          response=$(curl -sS -L -H "Content-Type: application/json" -X POST -w "HTTPSTATUS:%{http_code}" "$URL")
          
          # Extraer código de estado
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -e 's/HTTPSTATUS\:.*//g')
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          # Verificar si fue exitoso
          if [ $http_code -eq 200 ]; then
            echo "✅ Report sent successfully!"
          else
            echo "❌ Failed to send report"
            exit 1
          fi
