name: Daily API Report

on:
  schedule:
    # Ejecuta cada 3 horas 
    - cron: '0 */3 * * *'
  
  # Permite ejecución manual desde GitHub
  workflow_dispatch:
    inputs:
      startDate:
        description: 'Fecha de inicio (YYYY-MM-DD)'
        required: false
        type: string
      endDate:
        description: 'Fecha de fin (YYYY-MM-DD)'
        required: false
        type: string

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send API Report
        run: |
          # Construir URL con parámetros opcionales
          URL="${{ secrets.APP_URL }}/trigger-report"
          
          # Si se proporcionan inputs manuales, usarlos (start y/o end). Si no, por defecto: desde siempre hasta hoy
          if [ -n "${{ github.event.inputs.startDate }}" ] || [ -n "${{ github.event.inputs.endDate }}" ]; then
            SEP="?"
            if [ -n "${{ github.event.inputs.startDate }}" ]; then
              URL="${URL}${SEP}startDate=${{ github.event.inputs.startDate }}"
              SEP="&"
            fi
            if [ -n "${{ github.event.inputs.endDate }}" ]; then
              URL="${URL}${SEP}endDate=${{ github.event.inputs.endDate }}"
            fi
          else
            # "Para siempre": fijar una fecha de inicio muy temprana y dejar endDate vacío (el servidor usa hoy por defecto)
            URL="${URL}?startDate=2000-01-01"
          fi
          
          echo "Triggering report at: $URL"
          
          # Hacer la petición GET al endpoint
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X GET "$URL")
          
          # Extraer código de estado
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -e 's/HTTPSTATUS\:.*//g')
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          # Verificar si fue exitoso
          if [ $http_code -eq 200 ]; then
            echo "✅ Report sent successfully!"
          else
            echo "❌ Failed to send report"
            exit 1
          fi
